export async function ensureBillingErrorSchema(client) {
  await client.query(`
    CREATE TABLE IF NOT EXISTS billing_error_reports (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      unit_bill_id BIGINT NOT NULL REFERENCES unit_bills(id) ON DELETE CASCADE,
      reported_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      category VARCHAR(30) NOT NULL,
      description VARCHAR(1500) NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
      resolution_note VARCHAR(1500) NULL,
      resolved_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
      resolved_at TIMESTAMPTZ NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  // A resident may submit up to three reports for a given SOA. The route
  // enforces that limit while holding the SOA row lock, rather than using a
  // one-open-report unique index.
  await client.query("DROP INDEX IF EXISTS billing_error_reports_open_reporter_bill_unique");
  await client.query("CREATE INDEX IF NOT EXISTS billing_error_reports_status_created_idx ON billing_error_reports (status, created_at DESC)");
}
