const billTotalSql = `COALESCE((SELECT ROUND(SUM(c.quantity * c.rate_applied), 2) FROM bill_charges c WHERE c.unit_bill_id = b.id), 0)`;
const billAppliedSql = `COALESCE((SELECT ROUND(SUM(pa.amount_applied), 2) FROM payment_applications pa WHERE pa.unit_bill_id = b.id), 0)`;
const paymentAppliedSql = `COALESCE((SELECT ROUND(SUM(pa.amount_applied), 2) FROM payment_applications pa WHERE pa.payment_submission_id = ps.id), 0)`;

export async function ensurePaymentLedgerSchema(client) {
  await client.query(`
    ALTER TABLE payment_submissions
    ADD COLUMN IF NOT EXISTS unit_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS entry_type VARCHAR(30) NOT NULL DEFAULT 'RECEIPT_UPLOAD',
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(30) NULL
  `);
  await client.query("ALTER TABLE payment_submissions ALTER COLUMN receipt_path DROP NOT NULL");
  await client.query("ALTER TABLE payment_submissions ALTER COLUMN receipt_original_name DROP NOT NULL");
  await client.query("ALTER TABLE payment_submissions ALTER COLUMN receipt_mime_type DROP NOT NULL");
  await client.query("ALTER TABLE payment_submissions ALTER COLUMN receipt_sha256 DROP NOT NULL");
  await client.query("ALTER TABLE payment_submissions ALTER COLUMN ocr_quality_status DROP NOT NULL");
  await client.query(`
    UPDATE payment_submissions
    SET payment_method = 'OTHER'
    WHERE review_status = 'APPROVED'
      AND payment_method IS NULL
  `);
  await client.query(`
    CREATE TABLE IF NOT EXISTS payment_applications (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      payment_submission_id BIGINT NOT NULL REFERENCES payment_submissions(id) ON DELETE CASCADE,
      unit_bill_id BIGINT NOT NULL REFERENCES unit_bills(id) ON DELETE CASCADE,
      amount_applied NUMERIC(12, 2) NOT NULL CHECK (amount_applied > 0),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await client.query(`
    CREATE TABLE IF NOT EXISTS payment_submission_targets (
      payment_submission_id BIGINT PRIMARY KEY REFERENCES payment_submissions(id) ON DELETE CASCADE,
      unit_bill_id BIGINT NOT NULL REFERENCES unit_bills(id) ON DELETE RESTRICT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await client.query("CREATE INDEX IF NOT EXISTS payment_submissions_unit_idx ON payment_submissions(unit_id)");
  await client.query("CREATE INDEX IF NOT EXISTS payment_submissions_method_idx ON payment_submissions(payment_method)");
  await client.query("CREATE INDEX IF NOT EXISTS payment_submissions_entry_type_idx ON payment_submissions(entry_type)");
  await client.query("CREATE INDEX IF NOT EXISTS payment_applications_payment_idx ON payment_applications(payment_submission_id)");
  await client.query("CREATE INDEX IF NOT EXISTS payment_applications_bill_idx ON payment_applications(unit_bill_id)");
  await client.query("CREATE INDEX IF NOT EXISTS payment_submission_targets_bill_idx ON payment_submission_targets(unit_bill_id)");
}

function cents(value) {
  const number = Number(value || 0);
  return Math.round(number * 100);
}

function moneyFromCents(value) {
  return Number((value / 100).toFixed(2));
}

export function allocateCredit({ billRemaining, paymentCredits }) {
  let remainingCents = cents(billRemaining);
  const applications = [];
  for (const payment of paymentCredits || []) {
    if (remainingCents <= 0) break;
    const availableCents = cents(payment.availableAmount);
    if (availableCents <= 0) continue;
    const appliedCents = Math.min(remainingCents, availableCents);
    applications.push({
      paymentSubmissionId: payment.paymentSubmissionId,
      amountApplied: moneyFromCents(appliedCents),
    });
    remainingCents -= appliedCents;
  }
  return { applications, remainingBalance: moneyFromCents(remainingCents) };
}

export function manualReference(paymentMethod, paymentId) {
  const prefix = paymentMethod === "CASH" ? "CASH" : paymentMethod.replaceAll("_", "");
  return `${prefix}-${String(paymentId).padStart(8, "0")}`;
}

export async function getUnitCreditBalance(client, unitId) {
  const result = await client.query(
    `SELECT COALESCE(ROUND(SUM(ps.verified_amount - ${paymentAppliedSql}), 2), 0) AS balance
     FROM payment_submissions ps
     WHERE ps.unit_id = $1 AND ps.review_status = 'APPROVED'`,
    [unitId],
  );
  return Number(result.rows[0]?.balance || 0);
}

export async function applyUnitCreditToBill(client, billId, preferredPaymentId = null) {
  const billResult = await client.query(
    `SELECT b.id, b.unit_id AS "unitId", ${billTotalSql} AS total, ${billAppliedSql} AS applied
     FROM unit_bills b WHERE b.id = $1`,
    [billId],
  );
  const bill = billResult.rows[0];
  if (!bill) return { appliedAmount: 0, remainingBalance: 0 };

  const remaining = Number(bill.total) - Number(bill.applied);
  if (remaining <= 0.005) return { appliedAmount: 0, remainingBalance: 0 };

  const creditsResult = await client.query(
    `SELECT ps.id AS "paymentSubmissionId",
       ROUND(ps.verified_amount - ${paymentAppliedSql}, 2) AS "availableAmount"
     FROM payment_submissions ps
     WHERE ps.unit_id = $1
       AND ps.review_status = 'APPROVED'
       AND ps.verified_amount - ${paymentAppliedSql} > 0.005
     ORDER BY
       CASE WHEN ps.id = $2 THEN 0 ELSE 1 END,
       ps.verified_payment_date,
       ps.submitted_at,
       ps.id`,
    [bill.unitId, preferredPaymentId],
  );

  const allocation = allocateCredit({ billRemaining: remaining, paymentCredits: creditsResult.rows });
  for (const application of allocation.applications) {
    await client.query(
      `INSERT INTO payment_applications (payment_submission_id, unit_bill_id, amount_applied)
       VALUES ($1, $2, $3)`,
      [application.paymentSubmissionId, billId, application.amountApplied],
    );
  }

  const appliedAmount = allocation.applications.reduce((sum, row) => sum + Number(row.amountApplied), 0);
  return { appliedAmount: Number(appliedAmount.toFixed(2)), remainingBalance: allocation.remainingBalance };
}

export async function applyUnitCreditToOpenBills(client, unitId, preferredBillId = null, preferredPaymentId = null) {
  let appliedAmount = 0;
  if (preferredBillId) {
    const preferred = await applyUnitCreditToBill(client, preferredBillId, preferredPaymentId);
    appliedAmount += preferred.appliedAmount;
  }

  const billsResult = await client.query(
    `SELECT b.id
     FROM unit_bills b
     JOIN billing_periods p ON p.id = b.billing_period_id
     WHERE b.unit_id = $1
       AND p.status IN ('GENERATED', 'FORWARDED', 'CLOSED')
       AND ${billAppliedSql} < ${billTotalSql}
     ORDER BY b.period_start_snapshot, b.id`,
    [unitId],
  );
  for (const bill of billsResult.rows) {
    if (preferredBillId && Number(bill.id) === Number(preferredBillId)) continue;
    if (await getUnitCreditBalance(client, unitId) <= 0.005) break;
    const result = await applyUnitCreditToBill(client, bill.id, preferredPaymentId);
    appliedAmount += result.appliedAmount;
  }
  return Number(appliedAmount.toFixed(2));
}

export { billAppliedSql, billTotalSql, paymentAppliedSql };
