import { selectConsecutiveReadings, WINDOW_SIZE } from './predictiveAnalytics.js';

const ACTIVE_STATUSES = ['OPEN', 'ACKNOWLEDGED'];
export const HIGH_USAGE_THRESHOLD = 0.3;

export const RECOMMENDATION_TYPES = {
  REVIEW_METER_READING: 'REVIEW_METER_READING',
  COLLECT_MORE_HISTORY: 'COLLECT_MORE_HISTORY',
  CHECK_HIGH_USAGE: 'CHECK_HIGH_USAGE',
};

function number(value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function latestReading(history) {
  return [...(history || [])].sort((left, right) => String(left.periodStart).localeCompare(String(right.periodStart))).at(-1);
}

export function buildPrescriptiveRecommendations({ forecast, history = [] }) {
  if (!forecast) return [];

  const latest = latestReading(history);
  if (forecast.status === 'FLAGGED_READING' || latest?.validationStatus === 'FLAGGED') {
    return [{
      recommendationType: RECOMMENDATION_TYPES.REVIEW_METER_READING,
      priority: 'HIGH',
      message: 'Review the latest meter reading before using it for billing or forecasting.',
      evidence: {
        reason: forecast.reason || latest?.validationNotes || 'The latest meter reading needs review.',
        latestPeriod: latest?.periodStart || null,
      },
    }];
  }

  const selected = selectConsecutiveReadings(history, WINDOW_SIZE);
  if (forecast.status === 'INSUFFICIENT_DATA') {
    const sampleCount = Math.min(Number(forecast.sampleCount ?? selected.length) || 0, WINDOW_SIZE);
    const missingMonths = Math.max(WINDOW_SIZE - sampleCount, 1);
    return [{
      recommendationType: RECOMMENDATION_TYPES.COLLECT_MORE_HISTORY,
      priority: 'MEDIUM',
      message: `Record ${missingMonths} more consecutive valid monthly meter reading${missingMonths === 1 ? '' : 's'} before relying on a forecast.`,
      evidence: { sampleCount, missingMonths, requiredMonths: WINDOW_SIZE },
    }];
  }

  if (forecast.status !== 'READY' || selected.length < WINDOW_SIZE) return [];
  const average = selected.reduce((sum, reading) => sum + (number(reading.consumption) || 0), 0) / selected.length;
  const predicted = number(forecast.predictedConsumption);
  if (average <= 0 || predicted === null || predicted < average * (1 + HIGH_USAGE_THRESHOLD)) return [];

  const increasePercent = Number((((predicted - average) / average) * 100).toFixed(2));
  return [{
    recommendationType: RECOMMENDATION_TYPES.CHECK_HIGH_USAGE,
    priority: 'HIGH',
    message: `Projected water use is ${Math.round(increasePercent)}% above the recent average. Check the meter and inspect for possible leaks or unusual use.`,
    evidence: {
      predictedConsumption: Number(predicted.toFixed(3)),
      recentAverage: Number(average.toFixed(3)),
      increasePercent,
      thresholdPercent: HIGH_USAGE_THRESHOLD * 100,
    },
  }];
}

export async function ensurePrescriptiveAnalyticsSchema(client) {
  await client.query(`
    CREATE TABLE IF NOT EXISTS prescriptive_recommendations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      unit_id BIGINT NOT NULL REFERENCES units(id) ON DELETE CASCADE,
      based_on_period_id BIGINT NOT NULL REFERENCES billing_periods(id) ON DELETE CASCADE,
      forecast_id BIGINT NULL REFERENCES billing_forecasts(id) ON DELETE SET NULL,
      recommendation_type VARCHAR(50) NOT NULL CHECK (recommendation_type IN ('REVIEW_METER_READING', 'COLLECT_MORE_HISTORY', 'CHECK_HIGH_USAGE')),
      priority VARCHAR(20) NOT NULL CHECK (priority IN ('HIGH', 'MEDIUM')),
      status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', 'SUPERSEDED')),
      message VARCHAR(500) NOT NULL,
      evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
      resident_visible_at TIMESTAMPTZ NULL,
      resident_visible_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE (unit_id, based_on_period_id, recommendation_type)
    )
  `);
  await client.query(`
    CREATE TABLE IF NOT EXISTS prescriptive_recommendation_actions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      recommendation_id BIGINT NOT NULL REFERENCES prescriptive_recommendations(id) ON DELETE CASCADE,
      actor_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
      action VARCHAR(30) NOT NULL CHECK (action IN ('ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', 'SHARED_WITH_RESIDENT', 'SUPERSEDED')),
      note VARCHAR(500) NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await client.query('CREATE INDEX IF NOT EXISTS prescriptive_recommendations_active_idx ON prescriptive_recommendations(status, priority, updated_at DESC)');
  await client.query('CREATE INDEX IF NOT EXISTS prescriptive_recommendations_resident_idx ON prescriptive_recommendations(unit_id, resident_visible_at DESC) WHERE resident_visible_at IS NOT NULL');
  await client.query('CREATE INDEX IF NOT EXISTS prescriptive_recommendation_actions_history_idx ON prescriptive_recommendation_actions(recommendation_id, created_at DESC)');
}

async function supersedeInactiveRecommendations(client, latestPeriodId, desiredKeys) {
  const existing = await client.query(
    `SELECT id, unit_id AS "unitId", based_on_period_id AS "basedOnPeriodId", recommendation_type AS "recommendationType"
     FROM prescriptive_recommendations
     WHERE status = ANY($1::varchar[])`,
    [ACTIVE_STATUSES],
  );
  for (const recommendation of existing.rows) {
    const key = `${recommendation.unitId}:${recommendation.basedOnPeriodId}:${recommendation.recommendationType}`;
    if (Number(recommendation.basedOnPeriodId) === Number(latestPeriodId) && desiredKeys.has(key)) continue;
    const note = Number(recommendation.basedOnPeriodId) === Number(latestPeriodId)
      ? 'The source readings no longer require this recommendation.'
      : 'A newer live billing period is available.';
    await client.query(
      `UPDATE prescriptive_recommendations
       SET status = 'SUPERSEDED', updated_at = NOW()
       WHERE id = $1`,
      [recommendation.id],
    );
    await client.query(
      `INSERT INTO prescriptive_recommendation_actions (recommendation_id, action, note)
       VALUES ($1, 'SUPERSEDED', $2)`,
      [recommendation.id, note],
    );
  }
}

export async function regeneratePrescriptiveRecommendations(client) {
  await ensurePrescriptiveAnalyticsSchema(client);
  const periodResult = await client.query(
    `SELECT p.id, p.period_start AS "periodStart"
     FROM billing_periods p
     WHERE p.analytics_only = FALSE
       AND EXISTS (SELECT 1 FROM billing_forecasts f WHERE f.based_on_period_id = p.id)
     ORDER BY p.period_start DESC
     LIMIT 1`,
  );
  const period = periodResult.rows[0];
  if (!period) return [];

  const [forecastsResult, historyResult] = await Promise.all([
    client.query(
      `SELECT f.id AS "forecastId", f.unit_id AS "unitId", f.forecast_status AS status,
        f.status_reason AS reason, f.sample_count AS "sampleCount",
        f.predicted_consumption AS "predictedConsumption"
       FROM billing_forecasts f
       WHERE f.based_on_period_id = $1`,
      [period.id],
    ),
    client.query(
      `SELECT m.unit_id AS "unitId", p.period_start AS "periodStart",
        m.current_reading - m.previous_reading AS consumption,
        m.validation_status AS "validationStatus", m.validation_notes AS "validationNotes"
       FROM meter_readings m
       JOIN billing_periods p ON p.id = m.billing_period_id
       WHERE p.period_start <= $1
       ORDER BY m.unit_id, p.period_start`,
      [period.periodStart],
    ),
  ]);

  const historyByUnit = new Map();
  for (const reading of historyResult.rows) {
    const unitId = Number(reading.unitId);
    if (!historyByUnit.has(unitId)) historyByUnit.set(unitId, []);
    historyByUnit.get(unitId).push(reading);
  }

  const desired = forecastsResult.rows.flatMap((forecast) => buildPrescriptiveRecommendations({
    forecast,
    history: historyByUnit.get(Number(forecast.unitId)) || [],
  }).map((recommendation) => ({ ...recommendation, unitId: Number(forecast.unitId), forecastId: forecast.forecastId })));
  const desiredKeys = new Set(desired.map((recommendation) => `${recommendation.unitId}:${period.id}:${recommendation.recommendationType}`));
  await supersedeInactiveRecommendations(client, period.id, desiredKeys);

  for (const recommendation of desired) {
    await client.query(
      `INSERT INTO prescriptive_recommendations
        (unit_id, based_on_period_id, forecast_id, recommendation_type, priority, message, evidence)
       VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb)
       ON CONFLICT (unit_id, based_on_period_id, recommendation_type) DO UPDATE
       SET forecast_id = EXCLUDED.forecast_id,
           priority = EXCLUDED.priority,
           message = EXCLUDED.message,
           evidence = EXCLUDED.evidence,
           status = CASE WHEN prescriptive_recommendations.status = 'SUPERSEDED' THEN 'OPEN' ELSE prescriptive_recommendations.status END,
           updated_at = NOW()`,
      [recommendation.unitId, period.id, recommendation.forecastId, recommendation.recommendationType,
        recommendation.priority, recommendation.message, JSON.stringify(recommendation.evidence)],
    );
  }

  return desired;
}
