-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    actor_user_id bigint NOT NULL,
    entity_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    entity_id bigint,
    action character varying(50) COLLATE pg_catalog."default" NOT NULL,
    old_values jsonb,
    new_values jsonb,
    remarks text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bill_charges
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unit_bill_id bigint NOT NULL,
    charge_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(12, 3) NOT NULL,
    rate_applied numeric(12, 2) NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT bill_charges_pkey PRIMARY KEY (id),
    CONSTRAINT bill_charges_bill_type_unique UNIQUE (unit_bill_id, charge_type)
);

CREATE TABLE IF NOT EXISTS public.billing_forecasts
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unit_id bigint NOT NULL,
    based_on_period_id bigint NOT NULL,
    forecast_for_month date NOT NULL,
    predicted_consumption numeric(12, 3),
    estimated_water_charge numeric(12, 2),
    model_name character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'LINEAR_REGRESSION_5_MONTH'::character varying,
    sample_count integer NOT NULL DEFAULT 0,
    slope numeric(16, 6),
    intercept numeric(16, 6),
    forecast_status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    status_reason character varying(255) COLLATE pg_catalog."default",
    generated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT billing_forecasts_pkey PRIMARY KEY (id),
    CONSTRAINT billing_forecasts_unit_period_unique UNIQUE (unit_id, based_on_period_id)
);

CREATE TABLE IF NOT EXISTS public.billing_periods
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    period_start date NOT NULL,
    period_end date NOT NULL,
    due_date date NOT NULL,
    water_rate_per_cubic_m numeric(12, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DRAFT'::character varying,
    created_by bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    association_dues_rate_per_sqm numeric(12, 2) NOT NULL,
    forwarded_at timestamp with time zone,
    forwarded_by bigint,
    readings_visible_at timestamp with time zone,
    period_type character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'LIVE_BILLING'::character varying,
    CONSTRAINT billing_periods_pkey PRIMARY KEY (id),
    CONSTRAINT billing_periods_start_unique UNIQUE (period_start)
);

CREATE TABLE IF NOT EXISTS public.meter_readings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unit_id bigint NOT NULL,
    billing_period_id bigint NOT NULL,
    recorded_by bigint NOT NULL,
    previous_reading numeric(12, 3) NOT NULL,
    current_reading numeric(12, 3) NOT NULL,
    validation_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VALID'::character varying,
    recorded_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    validation_notes text COLLATE pg_catalog."default",
    CONSTRAINT meter_readings_pkey PRIMARY KEY (id),
    CONSTRAINT meter_readings_unit_period_unique UNIQUE (unit_id, billing_period_id)
);

CREATE TABLE IF NOT EXISTS public.payment_applications
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    payment_submission_id bigint NOT NULL,
    unit_bill_id bigint NOT NULL,
    amount_applied numeric(12, 2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT payment_applications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment_submissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    submitted_by bigint NOT NULL,
    receipt_path text COLLATE pg_catalog."default",
    receipt_original_name character varying(255) COLLATE pg_catalog."default",
    receipt_mime_type character varying(50) COLLATE pg_catalog."default",
    receipt_sha256 character(64) COLLATE pg_catalog."default",
    ocr_raw_text text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    ocr_confidence numeric(5, 2),
    ocr_quality_status character varying(20) COLLATE pg_catalog."default",
    ocr_amount numeric(12, 2),
    ocr_reference_no character varying(100) COLLATE pg_catalog."default",
    ocr_payment_date date,
    review_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    reviewed_by bigint,
    reviewed_at timestamp with time zone,
    verified_amount numeric(12, 2),
    verified_reference_no character varying(100) COLLATE pg_catalog."default",
    verified_payment_date date,
    remarks text COLLATE pg_catalog."default",
    submitted_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    unit_id bigint NOT NULL,
    entry_type character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'RECEIPT_UPLOAD'::character varying,
    payment_method character varying(30) COLLATE pg_catalog."default",
    target_unit_bill_id bigint,
    receipt_storage character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'LOCAL'::character varying,
    receipt_cloudinary_public_id text COLLATE pg_catalog."default",
    CONSTRAINT payment_submissions_pkey PRIMARY KEY (id),
    CONSTRAINT payment_submissions_receipt_hash_unique UNIQUE (receipt_sha256)
);

CREATE TABLE IF NOT EXISTS public.prescriptive_recommendations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unit_id bigint NOT NULL,
    based_on_period_id bigint NOT NULL,
    forecast_id bigint,
    recommendation_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    priority character varying(20) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'OPEN'::character varying,
    message character varying(500) COLLATE pg_catalog."default" NOT NULL,
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
    resident_visible_at timestamp with time zone,
    resident_visible_by bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT prescriptive_recommendations_pkey PRIMARY KEY (id),
    CONSTRAINT prescriptive_recommendations_unit_id_based_on_period_id_rec_key UNIQUE (unit_id, based_on_period_id, recommendation_type)
);

CREATE TABLE IF NOT EXISTS public.soa_email_deliveries
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unit_bill_id bigint NOT NULL,
    recipient_user_id bigint,
    recipient_name character varying(150) COLLATE pg_catalog."default",
    recipient_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    attempt_count integer NOT NULL DEFAULT 0,
    last_error character varying(500) COLLATE pg_catalog."default",
    last_attempted_at timestamp with time zone,
    sent_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT soa_email_deliveries_pkey PRIMARY KEY (id),
    CONSTRAINT soa_email_deliveries_bill_email_unique UNIQUE (unit_bill_id, recipient_email)
);

CREATE TABLE IF NOT EXISTS public.soa_templates
(
    id smallint NOT NULL DEFAULT 1,
    template_data jsonb NOT NULL,
    updated_by bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT soa_templates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.unit_assignments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unit_id bigint NOT NULL,
    user_id bigint NOT NULL,
    relationship_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    is_primary_payer boolean NOT NULL DEFAULT false,
    start_date date NOT NULL DEFAULT CURRENT_DATE,
    end_date date,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT unit_assignments_pkey PRIMARY KEY (id),
    CONSTRAINT unit_assignments_unique_assignment UNIQUE (unit_id, user_id, start_date)
);

CREATE TABLE IF NOT EXISTS public.unit_bills
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unit_id bigint NOT NULL,
    billing_period_id bigint NOT NULL,
    generated_by bigint NOT NULL,
    soa_generated_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    unit_number_snapshot character varying(30) COLLATE pg_catalog."default" NOT NULL,
    payer_name_snapshot character varying(150) COLLATE pg_catalog."default",
    payer_email_snapshot character varying(255) COLLATE pg_catalog."default",
    period_start_snapshot date NOT NULL,
    period_end_snapshot date NOT NULL,
    statement_date date NOT NULL,
    due_date_snapshot date NOT NULL,
    previous_reading_snapshot numeric(12, 3),
    current_reading_snapshot numeric(12, 3),
    generation_warning character varying(255) COLLATE pg_catalog."default",
    published_at timestamp with time zone,
    published_by bigint,
    soa_template_snapshot jsonb,
    CONSTRAINT unit_bills_pkey PRIMARY KEY (id),
    CONSTRAINT unit_bills_unit_period_unique UNIQUE (unit_id, billing_period_id)
);

CREATE TABLE IF NOT EXISTS public.units
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    unit_number character varying(30) COLLATE pg_catalog."default" NOT NULL,
    floor character varying(20) COLLATE pg_catalog."default" NOT NULL,
    occupancy_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'VACANT'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    billable_area_sqm numeric(10, 2),
    CONSTRAINT units_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    full_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'RESIDENT'::character varying,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_actor_fk FOREIGN KEY (actor_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS audit_logs_actor_idx
    ON public.audit_logs(actor_user_id);


ALTER TABLE IF EXISTS public.bill_charges
    ADD CONSTRAINT bill_charges_unit_bill_id_fkey FOREIGN KEY (unit_bill_id)
    REFERENCES public.unit_bills (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.billing_forecasts
    ADD CONSTRAINT billing_forecasts_period_fk FOREIGN KEY (based_on_period_id)
    REFERENCES public.billing_periods (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.billing_forecasts
    ADD CONSTRAINT billing_forecasts_unit_fk FOREIGN KEY (unit_id)
    REFERENCES public.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.billing_periods
    ADD CONSTRAINT billing_periods_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.billing_periods
    ADD CONSTRAINT billing_periods_forwarded_by_fk FOREIGN KEY (forwarded_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.meter_readings
    ADD CONSTRAINT meter_readings_billing_period_id_fkey FOREIGN KEY (billing_period_id)
    REFERENCES public.billing_periods (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.meter_readings
    ADD CONSTRAINT meter_readings_recorded_by_fkey FOREIGN KEY (recorded_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.meter_readings
    ADD CONSTRAINT meter_readings_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES public.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.payment_applications
    ADD CONSTRAINT payment_applications_payment_submission_id_fkey FOREIGN KEY (payment_submission_id)
    REFERENCES public.payment_submissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS payment_applications_payment_idx
    ON public.payment_applications(payment_submission_id);


ALTER TABLE IF EXISTS public.payment_applications
    ADD CONSTRAINT payment_applications_unit_bill_id_fkey FOREIGN KEY (unit_bill_id)
    REFERENCES public.unit_bills (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS payment_applications_bill_idx
    ON public.payment_applications(unit_bill_id);


ALTER TABLE IF EXISTS public.payment_submissions
    ADD CONSTRAINT payment_submissions_reviewer_fk FOREIGN KEY (reviewed_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.payment_submissions
    ADD CONSTRAINT payment_submissions_submitter_fk FOREIGN KEY (submitted_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payment_submissions_submitter_idx
    ON public.payment_submissions(submitted_by);


ALTER TABLE IF EXISTS public.payment_submissions
    ADD CONSTRAINT payment_submissions_target_bill_fk FOREIGN KEY (target_unit_bill_id)
    REFERENCES public.unit_bills (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payment_submissions_target_bill_idx
    ON public.payment_submissions(target_unit_bill_id);


ALTER TABLE IF EXISTS public.payment_submissions
    ADD CONSTRAINT payment_submissions_unit_fk FOREIGN KEY (unit_id)
    REFERENCES public.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS payment_submissions_unit_idx
    ON public.payment_submissions(unit_id);


ALTER TABLE IF EXISTS public.prescriptive_recommendations
    ADD CONSTRAINT prescriptive_recommendations_based_on_period_id_fkey FOREIGN KEY (based_on_period_id)
    REFERENCES public.billing_periods (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.prescriptive_recommendations
    ADD CONSTRAINT prescriptive_recommendations_forecast_id_fkey FOREIGN KEY (forecast_id)
    REFERENCES public.billing_forecasts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.prescriptive_recommendations
    ADD CONSTRAINT prescriptive_recommendations_resident_visible_by_fkey FOREIGN KEY (resident_visible_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.prescriptive_recommendations
    ADD CONSTRAINT prescriptive_recommendations_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES public.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.soa_email_deliveries
    ADD CONSTRAINT soa_email_deliveries_recipient_user_id_fkey FOREIGN KEY (recipient_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.soa_email_deliveries
    ADD CONSTRAINT soa_email_deliveries_unit_bill_id_fkey FOREIGN KEY (unit_bill_id)
    REFERENCES public.unit_bills (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS soa_email_deliveries_bill_idx
    ON public.soa_email_deliveries(unit_bill_id);


ALTER TABLE IF EXISTS public.unit_assignments
    ADD CONSTRAINT fk_unit_assignments_unit FOREIGN KEY (unit_id)
    REFERENCES public.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS unit_assignments_active_primary_payer_unique
    ON public.unit_assignments(unit_id);


ALTER TABLE IF EXISTS public.unit_assignments
    ADD CONSTRAINT fk_unit_assignments_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.unit_bills
    ADD CONSTRAINT unit_bills_billing_period_id_fkey FOREIGN KEY (billing_period_id)
    REFERENCES public.billing_periods (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.unit_bills
    ADD CONSTRAINT unit_bills_generated_by_fkey FOREIGN KEY (generated_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.unit_bills
    ADD CONSTRAINT unit_bills_published_by_fk FOREIGN KEY (published_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.unit_bills
    ADD CONSTRAINT unit_bills_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES public.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

END;