BEGIN;

-- Change UNIT_OWNER to the broader RESIDENT role.
ALTER TABLE users
DROP CONSTRAINT IF EXISTS users_role_check;

UPDATE users
SET role = 'RESIDENT'
WHERE role = 'UNIT_OWNER';

ALTER TABLE users
ALTER COLUMN role SET DEFAULT 'RESIDENT';

ALTER TABLE users
ADD CONSTRAINT users_role_check
CHECK (role IN ('ADMIN', 'COLLECTOR', 'RESIDENT'));


-- Automatically updates updated_at whenever a row changes.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- Physical condominium units.
CREATE TABLE IF NOT EXISTS units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_number VARCHAR(30) NOT NULL,
    floor VARCHAR(20) NOT NULL,
    billable_area_sqm NUMERIC(10, 2) NULL,
    occupancy_status VARCHAR(20) NOT NULL DEFAULT 'VACANT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT units_billable_area_check
        CHECK (billable_area_sqm IS NULL OR billable_area_sqm > 0),

    CONSTRAINT units_occupancy_status_check
        CHECK (occupancy_status IN ('OCCUPIED', 'VACANT'))
);

CREATE UNIQUE INDEX IF NOT EXISTS units_unit_number_lower_unique
ON units (LOWER(unit_number));


DROP TRIGGER IF EXISTS units_set_updated_at ON units;

CREATE TRIGGER units_set_updated_at
BEFORE UPDATE ON units
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- Connects residents to units and controls unit-level access.
CREATE TABLE IF NOT EXISTS unit_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    unit_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    relationship_type VARCHAR(20) NOT NULL,
    is_primary_payer BOOLEAN NOT NULL DEFAULT FALSE,

    start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    end_date DATE NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_unit_assignments_unit
        FOREIGN KEY (unit_id)
        REFERENCES units(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_unit_assignments_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT unit_assignments_relationship_type_check
        CHECK (relationship_type IN ('OWNER', 'TENANT')),

    CONSTRAINT unit_assignments_dates_check
        CHECK (end_date IS NULL OR end_date >= start_date),

    CONSTRAINT unit_assignments_unique_assignment
        UNIQUE (unit_id, user_id, start_date)
);


-- One active assignment for the same resident and unit.
CREATE UNIQUE INDEX IF NOT EXISTS unit_assignments_active_user_unit_unique
ON unit_assignments (unit_id, user_id)
WHERE end_date IS NULL;


-- Only one current primary payer per unit.
CREATE UNIQUE INDEX IF NOT EXISTS unit_assignments_active_primary_payer_unique
ON unit_assignments (unit_id)
WHERE is_primary_payer = TRUE
  AND end_date IS NULL;


DROP TRIGGER IF EXISTS unit_assignments_set_updated_at ON unit_assignments;

CREATE TRIGGER unit_assignments_set_updated_at
BEFORE UPDATE ON unit_assignments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
