BEGIN;

-- One monthly billing cycle, such as June 2026.
CREATE TABLE IF NOT EXISTS billing_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    due_date DATE NOT NULL,

    water_rate_per_cubic_m NUMERIC(12, 2) NOT NULL,
    association_dues_rate_per_sqm NUMERIC(12, 2) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    created_by BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT billing_periods_dates_check
        CHECK (period_end >= period_start),

    CONSTRAINT billing_periods_due_date_check
        CHECK (due_date >= period_end),

    CONSTRAINT billing_periods_water_rate_check
        CHECK (water_rate_per_cubic_m >= 0),

    CONSTRAINT billing_periods_association_rate_check
        CHECK (association_dues_rate_per_sqm >= 0),

    CONSTRAINT billing_periods_status_check
        CHECK (status IN ('DRAFT', 'GENERATED', 'CLOSED')),

    CONSTRAINT billing_periods_created_by_fk
        FOREIGN KEY (created_by)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT billing_periods_start_unique
        UNIQUE (period_start)
);


DROP TRIGGER IF EXISTS billing_periods_set_updated_at ON billing_periods;
CREATE TRIGGER billing_periods_set_updated_at
BEFORE UPDATE ON billing_periods
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- Water meter reading for one unit during one billing period.
CREATE TABLE IF NOT EXISTS meter_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    unit_id BIGINT NOT NULL,
    billing_period_id BIGINT NOT NULL,
    recorded_by BIGINT NOT NULL,

    previous_reading NUMERIC(12, 3) NOT NULL,
    current_reading NUMERIC(12, 3) NOT NULL,

    meter_photo_url TEXT NULL,

    validation_status VARCHAR(20) NOT NULL DEFAULT 'VALID',

    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT meter_readings_unit_fk
        FOREIGN KEY (unit_id)
        REFERENCES units(id)
        ON DELETE RESTRICT,

    CONSTRAINT meter_readings_billing_period_fk
        FOREIGN KEY (billing_period_id)
        REFERENCES billing_periods(id)
        ON DELETE RESTRICT,

    CONSTRAINT meter_readings_recorded_by_fk
        FOREIGN KEY (recorded_by)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    CONSTRAINT meter_readings_validation_status_check
        CHECK (validation_status IN ('VALID', 'FLAGGED')),

    -- A lower current reading is only allowed if the collector flags it.
    CONSTRAINT meter_readings_reading_order_check
        CHECK (
            validation_status = 'FLAGGED'
            OR current_reading >= previous_reading
        ),

    -- One reading only per unit for each monthly billing cycle.
    CONSTRAINT meter_readings_unit_period_unique
        UNIQUE (unit_id, billing_period_id)
);


DROP TRIGGER IF EXISTS meter_readings_set_updated_at ON meter_readings;
CREATE TRIGGER meter_readings_set_updated_at
BEFORE UPDATE ON meter_readings
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- One bill for one unit during one billing period.
CREATE TABLE IF NOT EXISTS unit_bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    unit_id BIGINT NOT NULL,
    billing_period_id BIGINT NOT NULL,
    generated_by BIGINT NOT NULL,

    soa_file_url TEXT NULL,
    soa_generated_at TIMESTAMPTZ NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT unit_bills_unit_fk
        FOREIGN KEY (unit_id)
        REFERENCES units(id)
        ON DELETE RESTRICT,

    CONSTRAINT unit_bills_billing_period_fk
        FOREIGN KEY (billing_period_id)
        REFERENCES billing_periods(id)
        ON DELETE RESTRICT,

    CONSTRAINT unit_bills_generated_by_fk
        FOREIGN KEY (generated_by)
        REFERENCES users(id)
        ON DELETE RESTRICT,

    -- Prevents two bills for the same unit in the same month.
    CONSTRAINT unit_bills_unit_period_unique
        UNIQUE (unit_id, billing_period_id)
);


DROP TRIGGER IF EXISTS unit_bills_set_updated_at ON unit_bills;
CREATE TRIGGER unit_bills_set_updated_at
BEFORE UPDATE ON unit_bills
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- Individual charge lines inside each unit bill.
-- Water and association dues remain separate, which is better for SOA generation.
CREATE TABLE IF NOT EXISTS bill_charges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    unit_bill_id BIGINT NOT NULL,

    charge_type VARCHAR(30) NOT NULL,

    quantity NUMERIC(12, 3) NOT NULL,
    rate_applied NUMERIC(12, 2) NOT NULL,

    description VARCHAR(255) NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT bill_charges_unit_bill_fk
        FOREIGN KEY (unit_bill_id)
        REFERENCES unit_bills(id)
        ON DELETE CASCADE,

    CONSTRAINT bill_charges_type_check
        CHECK (charge_type IN ('WATER', 'ASSOCIATION_DUES')),

    CONSTRAINT bill_charges_quantity_check
        CHECK (quantity >= 0),

    CONSTRAINT bill_charges_rate_check
        CHECK (rate_applied >= 0),

    -- One water charge and one association dues charge per bill.
    CONSTRAINT bill_charges_bill_type_unique
        UNIQUE (unit_bill_id, charge_type)
);

COMMIT;
