BEGIN;

ALTER TABLE billing_periods
ADD COLUMN IF NOT EXISTS forwarded_at TIMESTAMPTZ NULL,
ADD COLUMN IF NOT EXISTS forwarded_by BIGINT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'billing_periods_forwarded_by_fk'
    ) THEN
        ALTER TABLE billing_periods
        ADD CONSTRAINT billing_periods_forwarded_by_fk
        FOREIGN KEY (forwarded_by) REFERENCES users(id) ON DELETE RESTRICT;
    END IF;
END;
$$;

ALTER TABLE billing_periods DROP CONSTRAINT IF EXISTS billing_periods_status_check;
ALTER TABLE billing_periods
ADD CONSTRAINT billing_periods_status_check
CHECK (status IN ('DRAFT', 'GENERATED', 'FORWARDED', 'CLOSED'));

ALTER TABLE unit_bills
ADD COLUMN IF NOT EXISTS unit_number_snapshot VARCHAR(30) NULL,
ADD COLUMN IF NOT EXISTS payer_name_snapshot VARCHAR(150) NULL,
ADD COLUMN IF NOT EXISTS payer_email_snapshot VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS period_start_snapshot DATE NULL,
ADD COLUMN IF NOT EXISTS period_end_snapshot DATE NULL,
ADD COLUMN IF NOT EXISTS statement_date DATE NULL,
ADD COLUMN IF NOT EXISTS due_date_snapshot DATE NULL,
ADD COLUMN IF NOT EXISTS previous_reading_snapshot NUMERIC(12, 3) NULL,
ADD COLUMN IF NOT EXISTS current_reading_snapshot NUMERIC(12, 3) NULL;

UPDATE unit_bills b
SET
    unit_number_snapshot = COALESCE(b.unit_number_snapshot, u.unit_number),
    payer_name_snapshot = COALESCE(b.payer_name_snapshot, (
        SELECT usr.full_name FROM unit_assignments a
        JOIN users usr ON usr.id = a.user_id
        WHERE a.unit_id = b.unit_id AND a.end_date IS NULL
        ORDER BY a.is_primary_payer DESC, a.id LIMIT 1
    )),
    payer_email_snapshot = COALESCE(b.payer_email_snapshot, (
        SELECT usr.email FROM unit_assignments a
        JOIN users usr ON usr.id = a.user_id
        WHERE a.unit_id = b.unit_id AND a.end_date IS NULL
        ORDER BY a.is_primary_payer DESC, a.id LIMIT 1
    )),
    period_start_snapshot = COALESCE(b.period_start_snapshot, p.period_start),
    period_end_snapshot = COALESCE(b.period_end_snapshot, p.period_end),
    statement_date = COALESCE(b.statement_date, b.soa_generated_at::date, b.created_at::date),
    due_date_snapshot = COALESCE(b.due_date_snapshot, p.due_date),
    previous_reading_snapshot = COALESCE(b.previous_reading_snapshot, m.previous_reading),
    current_reading_snapshot = COALESCE(b.current_reading_snapshot, m.current_reading)
FROM units u, billing_periods p, meter_readings m
WHERE u.id = b.unit_id
  AND p.id = b.billing_period_id
  AND m.unit_id = b.unit_id
  AND m.billing_period_id = b.billing_period_id;

ALTER TABLE unit_bills
ALTER COLUMN unit_number_snapshot SET NOT NULL,
ALTER COLUMN period_start_snapshot SET NOT NULL,
ALTER COLUMN period_end_snapshot SET NOT NULL,
ALTER COLUMN statement_date SET NOT NULL,
ALTER COLUMN due_date_snapshot SET NOT NULL,
ALTER COLUMN previous_reading_snapshot SET NOT NULL,
ALTER COLUMN current_reading_snapshot SET NOT NULL;

CREATE TABLE IF NOT EXISTS billing_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_period_id BIGINT NULL,
    unit_bill_id BIGINT NULL,
    actor_id BIGINT NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    reason VARCHAR(500) NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT billing_events_period_fk
        FOREIGN KEY (billing_period_id) REFERENCES billing_periods(id) ON DELETE SET NULL,
    CONSTRAINT billing_events_bill_fk
        FOREIGN KEY (unit_bill_id) REFERENCES unit_bills(id) ON DELETE SET NULL,
    CONSTRAINT billing_events_actor_fk
        FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT billing_events_type_check
        CHECK (event_type IN ('GENERATED', 'SOA_EDITED', 'REOPENED', 'DELETED', 'FORWARDED'))
);

COMMIT;
