BEGIN;

ALTER TABLE unit_bills
ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ NULL,
ADD COLUMN IF NOT EXISTS published_by BIGINT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unit_bills_published_by_fk') THEN
        ALTER TABLE unit_bills
        ADD CONSTRAINT unit_bills_published_by_fk
        FOREIGN KEY (published_by) REFERENCES users(id) ON DELETE RESTRICT;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS payment_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_bill_id BIGINT NOT NULL,
    submitted_by BIGINT NOT NULL,
    receipt_path TEXT NOT NULL,
    receipt_original_name VARCHAR(255) NOT NULL,
    receipt_mime_type VARCHAR(50) NOT NULL,
    receipt_sha256 CHAR(64) NOT NULL,
    ocr_raw_text TEXT NOT NULL DEFAULT '',
    ocr_confidence NUMERIC(5, 2) NULL,
    ocr_quality_status VARCHAR(20) NOT NULL,
    ocr_amount NUMERIC(12, 2) NULL,
    ocr_reference_no VARCHAR(100) NULL,
    ocr_payment_date DATE NULL,
    review_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by BIGINT NULL,
    reviewed_at TIMESTAMPTZ NULL,
    verified_amount NUMERIC(12, 2) NULL,
    verified_reference_no VARCHAR(100) NULL,
    verified_payment_date DATE NULL,
    remarks TEXT NULL,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT payment_submissions_bill_fk FOREIGN KEY (unit_bill_id) REFERENCES unit_bills(id) ON DELETE RESTRICT,
    CONSTRAINT payment_submissions_submitter_fk FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT payment_submissions_reviewer_fk FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT payment_submissions_receipt_hash_unique UNIQUE (receipt_sha256),
    CONSTRAINT payment_submissions_mime_check CHECK (receipt_mime_type IN ('image/jpeg', 'image/png')),
    CONSTRAINT payment_submissions_quality_check CHECK (ocr_quality_status IN ('GOOD', 'BLURRY', 'LOW_RESOLUTION')),
    CONSTRAINT payment_submissions_status_check CHECK (review_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT payment_submissions_ocr_amount_check CHECK (ocr_amount IS NULL OR ocr_amount > 0),
    CONSTRAINT payment_submissions_verified_amount_check CHECK (verified_amount IS NULL OR verified_amount > 0),
    CONSTRAINT payment_submissions_review_check CHECK (
        (review_status = 'PENDING' AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR
        (review_status = 'APPROVED' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL
          AND verified_amount IS NOT NULL AND verified_reference_no IS NOT NULL AND verified_payment_date IS NOT NULL)
        OR
        (review_status = 'REJECTED' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL AND remarks IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS payment_submissions_bill_idx ON payment_submissions(unit_bill_id);
CREATE INDEX IF NOT EXISTS payment_submissions_submitter_idx ON payment_submissions(submitted_by);
CREATE INDEX IF NOT EXISTS payment_submissions_status_idx ON payment_submissions(review_status);
CREATE UNIQUE INDEX IF NOT EXISTS payment_submissions_approved_reference_unique
ON payment_submissions (LOWER(verified_reference_no))
WHERE review_status = 'APPROVED';

DROP TRIGGER IF EXISTS payment_submissions_set_updated_at ON payment_submissions;
CREATE TRIGGER payment_submissions_set_updated_at
BEFORE UPDATE ON payment_submissions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE billing_events DROP CONSTRAINT IF EXISTS billing_events_type_check;
ALTER TABLE billing_events ADD CONSTRAINT billing_events_type_check
CHECK (event_type IN ('GENERATED', 'SOA_EDITED', 'REOPENED', 'DELETED', 'FORWARDED', 'PUBLISHED'));

COMMIT;
