BEGIN;

ALTER TABLE meter_readings
ADD COLUMN IF NOT EXISTS validation_notes TEXT NULL;

WITH ordered_readings AS (
    SELECT m.id, m.previous_reading, m.current_reading,
        LAG(m.current_reading) OVER (PARTITION BY m.unit_id ORDER BY p.period_start) AS prior_current
    FROM meter_readings m
    JOIN billing_periods p ON p.id = m.billing_period_id
)
UPDATE meter_readings m
SET validation_status = 'FLAGGED',
    validation_notes = CONCAT_WS(' ',
        CASE WHEN assessed.current_reading < assessed.previous_reading
            THEN 'Present reading is lower than the previous reading.' END,
        CASE WHEN assessed.prior_current IS NOT NULL
                  AND ABS(assessed.prior_current - assessed.previous_reading) > 0.001
            THEN 'Previous reading does not match the last recorded present reading.' END)
FROM ordered_readings assessed
WHERE m.id = assessed.id
  AND (assessed.current_reading < assessed.previous_reading
       OR (assessed.prior_current IS NOT NULL
           AND ABS(assessed.prior_current - assessed.previous_reading) > 0.001));

CREATE TABLE IF NOT EXISTS billing_forecasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id BIGINT NOT NULL,
    based_on_period_id BIGINT NOT NULL,
    forecast_for_month DATE NOT NULL,
    predicted_consumption NUMERIC(12, 3) NULL,
    estimated_water_charge NUMERIC(12, 2) NULL,
    model_name VARCHAR(50) NOT NULL DEFAULT 'LINEAR_REGRESSION_5_MONTH',
    sample_count INTEGER NOT NULL DEFAULT 0,
    slope NUMERIC(16, 6) NULL,
    intercept NUMERIC(16, 6) NULL,
    forecast_status VARCHAR(30) NOT NULL,
    status_reason VARCHAR(255) NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT billing_forecasts_unit_fk
        FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT,
    CONSTRAINT billing_forecasts_period_fk
        FOREIGN KEY (based_on_period_id) REFERENCES billing_periods(id) ON DELETE CASCADE,
    CONSTRAINT billing_forecasts_status_check
        CHECK (forecast_status IN ('READY', 'INSUFFICIENT_DATA', 'FLAGGED_READING')),
    CONSTRAINT billing_forecasts_sample_count_check
        CHECK (sample_count >= 0),
    CONSTRAINT billing_forecasts_prediction_check
        CHECK (predicted_consumption IS NULL OR predicted_consumption >= 0),
    CONSTRAINT billing_forecasts_unit_period_unique
        UNIQUE (unit_id, based_on_period_id)
);

CREATE INDEX IF NOT EXISTS billing_forecasts_unit_month_idx
ON billing_forecasts(unit_id, forecast_for_month DESC);

CREATE INDEX IF NOT EXISTS billing_forecasts_month_idx
ON billing_forecasts(forecast_for_month DESC);

COMMIT;
