BEGIN;

ALTER TABLE payment_submissions
ADD COLUMN IF NOT EXISTS unit_id BIGINT NULL,
ADD COLUMN IF NOT EXISTS entry_type VARCHAR(30) NOT NULL DEFAULT 'RECEIPT_UPLOAD',
ADD COLUMN IF NOT EXISTS payment_method VARCHAR(30) NULL;

UPDATE payment_submissions ps
SET unit_id = b.unit_id
FROM unit_bills b
WHERE ps.unit_bill_id = b.id
  AND ps.unit_id IS NULL;

ALTER TABLE payment_submissions ALTER COLUMN unit_bill_id DROP NOT NULL;
ALTER TABLE payment_submissions ALTER COLUMN receipt_path DROP NOT NULL;
ALTER TABLE payment_submissions ALTER COLUMN receipt_original_name DROP NOT NULL;
ALTER TABLE payment_submissions ALTER COLUMN receipt_mime_type DROP NOT NULL;
ALTER TABLE payment_submissions ALTER COLUMN receipt_sha256 DROP NOT NULL;
ALTER TABLE payment_submissions ALTER COLUMN ocr_quality_status DROP NOT NULL;

UPDATE payment_submissions
SET payment_method = 'OTHER'
WHERE review_status = 'APPROVED'
  AND payment_method IS NULL;

ALTER TABLE payment_submissions DROP CONSTRAINT IF EXISTS payment_submissions_mime_check;
ALTER TABLE payment_submissions DROP CONSTRAINT IF EXISTS payment_submissions_quality_check;
ALTER TABLE payment_submissions DROP CONSTRAINT IF EXISTS payment_submissions_review_check;
ALTER TABLE payment_submissions DROP CONSTRAINT IF EXISTS payment_submissions_entry_type_check;
ALTER TABLE payment_submissions DROP CONSTRAINT IF EXISTS payment_submissions_method_check;
ALTER TABLE payment_submissions DROP CONSTRAINT IF EXISTS payment_submissions_unit_fk;
ALTER TABLE payment_submissions DROP CONSTRAINT IF EXISTS payment_submissions_bill_or_unit_check;
ALTER TABLE payment_submissions DROP CONSTRAINT IF EXISTS payment_submissions_receipt_fields_check;

ALTER TABLE payment_submissions
ADD CONSTRAINT payment_submissions_entry_type_check
  CHECK (entry_type IN ('RECEIPT_UPLOAD', 'MANUAL')),
ADD CONSTRAINT payment_submissions_method_check
  CHECK (payment_method IS NULL OR payment_method IN ('GCASH', 'BANK_TRANSFER', 'CASH', 'OTHER')),
ADD CONSTRAINT payment_submissions_unit_fk
  FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT,
ADD CONSTRAINT payment_submissions_bill_or_unit_check
  CHECK (unit_bill_id IS NOT NULL OR unit_id IS NOT NULL),
ADD CONSTRAINT payment_submissions_receipt_fields_check
  CHECK (
    (entry_type = 'RECEIPT_UPLOAD'
      AND receipt_path IS NOT NULL
      AND receipt_original_name IS NOT NULL
      AND receipt_mime_type IN ('image/jpeg', 'image/png')
      AND receipt_sha256 IS NOT NULL
      AND ocr_quality_status IN ('GOOD', 'BLURRY', 'LOW_RESOLUTION'))
    OR
    (entry_type = 'MANUAL'
      AND receipt_path IS NULL
      AND receipt_original_name IS NULL
      AND receipt_mime_type IS NULL
      AND receipt_sha256 IS NULL
      AND ocr_quality_status IS NULL)
  ),
ADD CONSTRAINT payment_submissions_review_check CHECK (
    (review_status = 'PENDING' AND reviewed_by IS NULL AND reviewed_at IS NULL)
    OR
    (review_status = 'APPROVED' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL
      AND verified_amount IS NOT NULL AND verified_reference_no IS NOT NULL
      AND verified_payment_date IS NOT NULL AND payment_method IS NOT NULL)
    OR
    (review_status = 'REJECTED' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL AND remarks IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS payment_submissions_unit_idx ON payment_submissions(unit_id);
CREATE INDEX IF NOT EXISTS payment_submissions_method_idx ON payment_submissions(payment_method);
CREATE INDEX IF NOT EXISTS payment_submissions_entry_type_idx ON payment_submissions(entry_type);

CREATE TABLE IF NOT EXISTS payment_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_submission_id BIGINT NOT NULL,
    unit_bill_id BIGINT NOT NULL,
    amount_applied NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT payment_applications_payment_fk
      FOREIGN KEY (payment_submission_id) REFERENCES payment_submissions(id) ON DELETE CASCADE,
    CONSTRAINT payment_applications_bill_fk
      FOREIGN KEY (unit_bill_id) REFERENCES unit_bills(id) ON DELETE CASCADE,
    CONSTRAINT payment_applications_amount_check CHECK (amount_applied > 0)
);

CREATE INDEX IF NOT EXISTS payment_applications_payment_idx ON payment_applications(payment_submission_id);
CREATE INDEX IF NOT EXISTS payment_applications_bill_idx ON payment_applications(unit_bill_id);

INSERT INTO payment_applications (payment_submission_id, unit_bill_id, amount_applied)
SELECT ps.id, ps.unit_bill_id, ps.verified_amount
FROM payment_submissions ps
WHERE ps.review_status = 'APPROVED'
  AND ps.unit_bill_id IS NOT NULL
  AND ps.verified_amount IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM payment_applications pa WHERE pa.payment_submission_id = ps.id
  );

COMMIT;
