BEGIN;

CREATE TABLE IF NOT EXISTS prescriptive_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id BIGINT NOT NULL,
    based_on_period_id BIGINT NOT NULL,
    forecast_id BIGINT NULL,
    recommendation_type VARCHAR(50) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    message VARCHAR(500) NOT NULL,
    evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    resident_visible_at TIMESTAMPTZ NULL,
    resident_visible_by BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT prescriptive_recommendations_unit_fk
      FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE CASCADE,
    CONSTRAINT prescriptive_recommendations_period_fk
      FOREIGN KEY (based_on_period_id) REFERENCES billing_periods(id) ON DELETE CASCADE,
    CONSTRAINT prescriptive_recommendations_forecast_fk
      FOREIGN KEY (forecast_id) REFERENCES billing_forecasts(id) ON DELETE SET NULL,
    CONSTRAINT prescriptive_recommendations_visible_by_fk
      FOREIGN KEY (resident_visible_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT prescriptive_recommendations_type_check
      CHECK (recommendation_type IN ('REVIEW_METER_READING', 'COLLECT_MORE_HISTORY', 'CHECK_HIGH_USAGE')),
    CONSTRAINT prescriptive_recommendations_priority_check
      CHECK (priority IN ('HIGH', 'MEDIUM')),
    CONSTRAINT prescriptive_recommendations_status_check
      CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', 'SUPERSEDED')),
    CONSTRAINT prescriptive_recommendations_unit_period_type_unique
      UNIQUE (unit_id, based_on_period_id, recommendation_type)
);

CREATE INDEX IF NOT EXISTS prescriptive_recommendations_active_idx
ON prescriptive_recommendations(status, priority, updated_at DESC);

CREATE INDEX IF NOT EXISTS prescriptive_recommendations_resident_idx
ON prescriptive_recommendations(unit_id, resident_visible_at DESC)
WHERE resident_visible_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS prescriptive_recommendation_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT NOT NULL,
    actor_id BIGINT NULL,
    action VARCHAR(30) NOT NULL,
    note VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT prescriptive_recommendation_actions_recommendation_fk
      FOREIGN KEY (recommendation_id) REFERENCES prescriptive_recommendations(id) ON DELETE CASCADE,
    CONSTRAINT prescriptive_recommendation_actions_actor_fk
      FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT prescriptive_recommendation_actions_type_check
      CHECK (action IN ('ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', 'SHARED_WITH_RESIDENT', 'SUPERSEDED'))
);

CREATE INDEX IF NOT EXISTS prescriptive_recommendation_actions_history_idx
ON prescriptive_recommendation_actions(recommendation_id, created_at DESC);

COMMIT;
