BEGIN;

CREATE TABLE IF NOT EXISTS soa_email_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_bill_id BIGINT NOT NULL REFERENCES unit_bills(id) ON DELETE CASCADE,
    recipient_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    recipient_name VARCHAR(150) NULL,
    recipient_email VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(500) NULL,
    last_attempted_at TIMESTAMPTZ NULL,
    sent_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT soa_email_deliveries_status_check
        CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT soa_email_deliveries_attempt_count_check
        CHECK (attempt_count >= 0),
    CONSTRAINT soa_email_deliveries_bill_email_unique
        UNIQUE (unit_bill_id, recipient_email)
);

CREATE INDEX IF NOT EXISTS soa_email_deliveries_bill_idx
    ON soa_email_deliveries(unit_bill_id);

DROP TRIGGER IF EXISTS soa_email_deliveries_set_updated_at ON soa_email_deliveries;
CREATE TRIGGER soa_email_deliveries_set_updated_at
BEFORE UPDATE ON soa_email_deliveries
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
