BEGIN;

CREATE TABLE IF NOT EXISTS user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    notification_type VARCHAR(60) NOT NULL,
    title VARCHAR(180) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    href VARCHAR(500) NULL,
    dedupe_key VARCHAR(160) NULL,
    read_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT user_notifications_recipient_dedupe_unique
        UNIQUE (recipient_user_id, dedupe_key)
);

CREATE INDEX IF NOT EXISTS user_notifications_recipient_created_idx
    ON user_notifications (recipient_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS user_notifications_unread_idx
    ON user_notifications (recipient_user_id, read_at)
    WHERE read_at IS NULL;

COMMIT;
