BEGIN;

ALTER TABLE soa_templates
  ADD COLUMN IF NOT EXISTS logo_asset_public_id VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS logo_asset_mime_type VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS qr_asset_public_id VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS qr_asset_mime_type VARCHAR(100) NULL;

ALTER TABLE unit_bills
  ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS payment_note VARCHAR(1000) NULL,
  ADD COLUMN IF NOT EXISTS soa_revision INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS corrected_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS corrected_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS correction_reason VARCHAR(500) NULL;

CREATE UNIQUE INDEX IF NOT EXISTS unit_bills_invoice_number_unique
  ON unit_bills (LOWER(invoice_number))
  WHERE invoice_number IS NOT NULL AND BTRIM(invoice_number) <> '';

CREATE TABLE IF NOT EXISTS billing_error_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_bill_id BIGINT NOT NULL REFERENCES unit_bills(id) ON DELETE CASCADE,
  reported_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  category VARCHAR(30) NOT NULL CHECK (category IN ('METER_READING', 'WATER_CHARGE', 'ASSOCIATION_DUES', 'PAYMENT_OR', 'OTHER')),
  description VARCHAR(1500) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'RESOLVED')),
  resolution_note VARCHAR(1500) NULL,
  resolved_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  resolved_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS billing_error_reports_status_created_idx
  ON billing_error_reports (status, created_at DESC);

COMMIT;
