BEGIN;

CREATE TABLE IF NOT EXISTS soa_reminder_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_bill_id BIGINT NOT NULL REFERENCES unit_bills(id) ON DELETE CASCADE,
    recipient_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    recipient_name VARCHAR(150) NULL,
    recipient_email VARCHAR(255) NOT NULL,
    due_date DATE NOT NULL,
    reminder_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(500) NULL,
    last_attempted_at TIMESTAMPTZ NULL,
    sent_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT soa_reminder_deliveries_type_check
        CHECK (reminder_type IN ('DUE_SOON', 'DUE_TODAY', 'OVERDUE')),
    CONSTRAINT soa_reminder_deliveries_status_check
        CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'SKIPPED')),
    CONSTRAINT soa_reminder_deliveries_attempt_count_check
        CHECK (attempt_count >= 0),
    CONSTRAINT soa_reminder_deliveries_event_unique
        UNIQUE (unit_bill_id, recipient_email, due_date, reminder_type)
);

CREATE INDEX IF NOT EXISTS soa_reminder_deliveries_pending_idx
    ON soa_reminder_deliveries(status, attempt_count)
    WHERE status IN ('PENDING', 'FAILED', 'PROCESSING');

DROP TRIGGER IF EXISTS soa_reminder_deliveries_set_updated_at ON soa_reminder_deliveries;
CREATE TRIGGER soa_reminder_deliveries_set_updated_at
BEFORE UPDATE ON soa_reminder_deliveries
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
