BEGIN;

CREATE TABLE IF NOT EXISTS payment_ledger_policy (
  id INTEGER PRIMARY KEY CHECK (id = 1), version INTEGER NOT NULL,
  activated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
LOCK TABLE payment_submissions, payment_applications, unit_bills IN SHARE ROW EXCLUSIVE MODE;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM payment_ledger_policy WHERE id = 1 AND version = 2) THEN
    IF EXISTS (SELECT 1 FROM payment_submissions) OR EXISTS (SELECT 1 FROM payment_applications)
       OR EXISTS (SELECT 1 FROM unit_bills WHERE NULLIF(TRIM(invoice_number), '') IS NOT NULL) THEN
      RAISE EXCEPTION 'Category ledger activation blocked: legacy payment records/applications/invoice references remain. Run payments:preflight; no records have been deleted.';
    END IF;
  END IF;
END $$;

ALTER TABLE payment_submissions ADD COLUMN IF NOT EXISTS payment_purpose VARCHAR(30);
ALTER TABLE payment_submissions DROP CONSTRAINT IF EXISTS payment_submissions_purpose_check;
ALTER TABLE payment_submissions ADD CONSTRAINT payment_submissions_purpose_check
  CHECK (payment_purpose IN ('WATER', 'ASSOCIATION_DUES', 'COMBINED'));
ALTER TABLE payment_submissions ALTER COLUMN payment_purpose SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS category_payment_reference_unique
  ON payment_submissions(LOWER(BTRIM(verified_reference_no))) WHERE review_status='APPROVED';
ALTER TABLE payment_submissions DROP CONSTRAINT IF EXISTS category_payment_verified_amount_check;
ALTER TABLE payment_submissions ADD CONSTRAINT category_payment_verified_amount_check
  CHECK(verified_amount IS NULL OR (verified_amount > 0 AND verified_amount <> 'NaN'::numeric));

CREATE TABLE IF NOT EXISTS payment_charge_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_submission_id BIGINT NOT NULL REFERENCES payment_submissions(id) ON DELETE CASCADE,
  charge_type VARCHAR(30) NOT NULL CHECK (charge_type IN ('WATER', 'ASSOCIATION_DUES')),
  allocated_amount NUMERIC(12,2) NOT NULL CHECK (allocated_amount > 0 AND allocated_amount <> 'NaN'::numeric),
  invoice_number VARCHAR(100),
  UNIQUE (payment_submission_id, charge_type),
  UNIQUE (id, payment_submission_id)
);
ALTER TABLE payment_applications ADD COLUMN IF NOT EXISTS charge_allocation_id BIGINT;
ALTER TABLE payment_applications ADD COLUMN IF NOT EXISTS component VARCHAR(20);
ALTER TABLE payment_applications ALTER COLUMN charge_allocation_id SET NOT NULL;
ALTER TABLE payment_applications ALTER COLUMN component SET NOT NULL;
ALTER TABLE payment_applications DROP CONSTRAINT IF EXISTS payment_applications_allocation_fk;
ALTER TABLE payment_applications ADD CONSTRAINT payment_applications_allocation_fk
  FOREIGN KEY (charge_allocation_id, payment_submission_id)
  REFERENCES payment_charge_allocations(id, payment_submission_id) ON DELETE CASCADE;
ALTER TABLE payment_applications DROP CONSTRAINT IF EXISTS payment_applications_component_check;
ALTER TABLE payment_applications ADD CONSTRAINT payment_applications_component_check CHECK (component IN ('PRINCIPAL', 'LATE_PENALTY'));
ALTER TABLE payment_applications DROP CONSTRAINT IF EXISTS category_application_amount_check;
ALTER TABLE payment_applications ADD CONSTRAINT category_application_amount_check CHECK(amount_applied > 0 AND amount_applied <> 'NaN'::numeric);
CREATE INDEX IF NOT EXISTS payment_applications_allocation_idx ON payment_applications(charge_allocation_id);

-- Validate the final state of a transaction, not the intermediate approval INSERT.
CREATE OR REPLACE FUNCTION validate_category_payment_ledger() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM payment_submissions p LEFT JOIN payment_charge_allocations a ON a.payment_submission_id = p.id
    GROUP BY p.id HAVING (p.review_status = 'APPROVED' AND COALESCE(SUM(a.allocated_amount), 0) <> p.verified_amount)
      OR (p.review_status <> 'APPROVED' AND COUNT(a.id) > 0)
  ) THEN RAISE EXCEPTION 'Payment allocations do not reconcile' USING ERRCODE = '23514'; END IF;
  IF EXISTS (SELECT 1 FROM payment_charge_allocations a JOIN payment_submissions p ON p.id = a.payment_submission_id
    WHERE (p.payment_purpose = 'WATER' AND a.charge_type <> 'WATER')
       OR (p.payment_purpose = 'ASSOCIATION_DUES' AND a.charge_type <> 'ASSOCIATION_DUES')) THEN
    RAISE EXCEPTION 'Payment category mismatch' USING ERRCODE = '23514'; END IF;
  IF EXISTS (SELECT 1 FROM payment_charge_allocations a JOIN payment_applications x ON x.charge_allocation_id = a.id
    GROUP BY a.id HAVING SUM(x.amount_applied) > a.allocated_amount) THEN
    RAISE EXCEPTION 'Payment credit exceeded' USING ERRCODE = '23514'; END IF;
  IF EXISTS (SELECT 1 FROM payment_applications x JOIN payment_charge_allocations a ON a.id = x.charge_allocation_id
    JOIN payment_submissions p ON p.id = a.payment_submission_id JOIN unit_bills b ON b.id = x.unit_bill_id
    WHERE p.unit_id <> b.unit_id OR (x.component = 'LATE_PENALTY' AND a.charge_type <> 'ASSOCIATION_DUES')) THEN
    RAISE EXCEPTION 'Invalid payment application' USING ERRCODE = '23514'; END IF;
  IF EXISTS (SELECT 1 FROM payment_applications x JOIN payment_charge_allocations a ON a.id = x.charge_allocation_id
    JOIN unit_bills b ON b.id = x.unit_bill_id
    GROUP BY b.id, a.charge_type, x.component
    HAVING SUM(x.amount_applied) > CASE WHEN x.component = 'LATE_PENALTY' THEN b.late_penalty_amount
      ELSE COALESCE((SELECT ROUND(c.quantity * c.rate_applied, 2) FROM bill_charges c WHERE c.unit_bill_id = b.id AND c.charge_type = a.charge_type), 0) END) THEN
    RAISE EXCEPTION 'Charge balance exceeded' USING ERRCODE = '23514'; END IF;
  RETURN NULL;
END $$;
DROP TRIGGER IF EXISTS category_payment_submissions_check ON payment_submissions;
CREATE CONSTRAINT TRIGGER category_payment_submissions_check AFTER INSERT OR UPDATE OR DELETE ON payment_submissions
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_category_payment_ledger();
DROP TRIGGER IF EXISTS category_allocations_check ON payment_charge_allocations;
CREATE CONSTRAINT TRIGGER category_allocations_check AFTER INSERT OR UPDATE OR DELETE ON payment_charge_allocations
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_category_payment_ledger();
DROP TRIGGER IF EXISTS category_applications_check ON payment_applications;
CREATE CONSTRAINT TRIGGER category_applications_check AFTER INSERT OR UPDATE OR DELETE ON payment_applications
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_category_payment_ledger();
DROP TRIGGER IF EXISTS category_bill_charges_check ON bill_charges;
CREATE CONSTRAINT TRIGGER category_bill_charges_check AFTER INSERT OR UPDATE OR DELETE ON bill_charges
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_category_payment_ledger();
DROP TRIGGER IF EXISTS category_bill_balances_check ON unit_bills;
CREATE CONSTRAINT TRIGGER category_bill_balances_check AFTER UPDATE ON unit_bills
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_category_payment_ledger();

-- Clean-start activation: retain bills and audit the change from whole-SOA penalties.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM payment_ledger_policy WHERE id = 1 AND version = 2) THEN
    INSERT INTO audit_logs (actor_user_id, entity_name, entity_id, action, old_values, new_values, remarks)
    SELECT NULL, 'UNIT_BILL', b.id, 'CATEGORY_PENALTY_ACTIVATION',
      jsonb_build_object('latePenaltyAmount', b.late_penalty_amount),
      jsonb_build_object('latePenaltyAmount', CASE WHEN b.due_date_snapshot < (NOW() AT TIME ZONE 'Asia/Manila')::date THEN
        ROUND(COALESCE((SELECT quantity * rate_applied FROM bill_charges WHERE unit_bill_id = b.id AND charge_type = 'ASSOCIATION_DUES'),0) * b.late_penalty_percent_snapshot / 100,2) ELSE 0 END),
      'Clean-start category payment policy; no payments were reassigned.' FROM unit_bills b;
    UPDATE unit_bills b SET late_penalty_amount = CASE WHEN b.due_date_snapshot < (NOW() AT TIME ZONE 'Asia/Manila')::date THEN
      ROUND(COALESCE((SELECT quantity * rate_applied FROM bill_charges WHERE unit_bill_id = b.id AND charge_type = 'ASSOCIATION_DUES'),0) * b.late_penalty_percent_snapshot / 100,2) ELSE 0 END,
      late_penalty_applied_at = CASE WHEN b.due_date_snapshot < (NOW() AT TIME ZONE 'Asia/Manila')::date THEN NOW() ELSE NULL END;
    INSERT INTO payment_ledger_policy(id, version) VALUES(1,2);
  END IF;
END $$;
COMMIT;
